In [1]:
import numpy as n

In [3]:
# Q 1 : Write a NumPy program to convert a list of numeric values into a
# one-dimensional NumPy array.

a = [1, 3, 23, 53, 21, 52, 66, 743, 77, 73]
arr = n.array(a)
arr

array([  1,   3,  23,  53,  21,  52,  66, 743,  77,  73])

In [10]:
# Q 2 : Write a NumPy program to create a 4x4 matrix with values ranging from 7 to 15
b = n.linspace(7, 15, 16)
b.reshape(4, 4)

array([[ 7.        ,  7.53333333,  8.06666667,  8.6       ],
       [ 9.13333333,  9.66666667, 10.2       , 10.73333333],
       [11.26666667, 11.8       , 12.33333333, 12.86666667],
       [13.4       , 13.93333333, 14.46666667, 15.        ]])

In [14]:
# Q 5 : Write a NumPy program to create a 2d array with 1 on the border and 0 inside

array1 = n.ones((6, 6))
array1

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
array1[1:-1,1:-1] = 0

In [16]:
array1

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
# Q 14 : Write a NumPy program to create a new array of 3*5, filled with 2
ab = n.ones((3, 5))
ab[:, :] = 2
ab

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [27]:
# Q 15 : Write a NumPy program to create a 3-D array with ones on a diagonal
# and zeros elsewhere

arr2 = n.zeros((3, 3, 3))

In [28]:
arr2

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])