In [3]:
#  Q 1:Create a 4X2 integer array and Prints its attributes
# Note: The element must be a type of unsigned int16. And print the
# following Attributes. The shape of an array.
# Array dimensions.
# The Length of each element of the array in bytes.

import numpy as np
arr = np.array([[245, 689], [678, 986], [234, 453], [563, 987]])
arr.shape

(4, 2)

In [4]:
arr.ndim

2

In [6]:
arr.itemsize

4

In [8]:
# Q 2: Create a 5X2 integer array from a range between 100 to 200 such that the
# difference between each element is 10.
arr1 = np.linspace(100, 200, 10)
arr1

array([100.        , 111.11111111, 122.22222222, 133.33333333,
       144.44444444, 155.55555556, 166.66666667, 177.77777778,
       188.88888889, 200.        ])

In [12]:
# Q 3: Following is the provided numPy array. Return array of items by taking the
# third column from all rows
# sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
sampleArray[ ...,2]

array([33, 66, 99])

In [14]:
# Q 4 : Return array of odd rows and even columns from below numpy array
# sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24],
# [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
sampleArray[::2, 1::2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])

In [22]:
# Q 5 : Extract all odd numbers from arr
# Input:
# arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Desired output:
# #> array([1, 3, 5, 7, 9]

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a = []
for i in range(len(arr)):
    if arr[i]%2 != 0:
        a.append(arr[i])
np.array(a)

array([1, 3, 5, 7, 9])

In [24]:
# Q 7 : Array size
arr.size

10

In [30]:
# Q 10 : Create a 3x3 identity matrix

I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
i = np.identity(4)

In [32]:
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
# Q 11 :  Create a 3x3x3 array with random values
# import random as r
array1 = np.random.rand(3, 3, 3)
array1

array([[[0.35508076, 0.67488167, 0.35502355],
        [0.45410562, 0.92799553, 0.05919138],
        [0.61679962, 0.39191518, 0.69142527]],

       [[0.60351265, 0.70434515, 0.22520852],
        [0.88713308, 0.30218566, 0.83945588],
        [0.47091945, 0.4938378 , 0.60267892]],

       [[0.58619965, 0.80706166, 0.88369816],
        [0.58586356, 0.76734973, 0.25116117],
        [0.20884585, 0.71726833, 0.53231737]]])

In [44]:
#  Q 12 : Print the numpy version and the configuration

np.__version__ # Numpy Version

'1.23.5'

In [45]:
np.show_config() # Numpy Configuration

openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFI